import './globals.scss';
// import dynamic from 'next/dynamic';
import { Inter } from 'next/font/google';

// import Header from './_components/header/Header';

// const DynamicHeader = dynamic(() => import('./_components/header/Header'), {
//   ssr: false,
// });

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Header /> */}
        {/* <DynamicHeader /> */}
        {children}
      </body>
    </html>
  )
};
